---
name: Testing Workflow
on:
  push:
    branches:
      - initial
    paths:
      - 'molecule/*'


jobs:
  example:
    runs-on: ubuntu-latest
    steps:

      - run: |
          echo "Example text: {{ github.event.inputs.example }}"
          molecule --version
          terraform version

      - uses: actions/checkout@v2
      - name: example local action
        uses: ./.github/actions/example
